rated_instructors = {
    "TBD": {"fullName": "TBD"},
    "Chris Gilmore": {
        "fullName": "Chris Gilmore",
        "firstName": "Christopher",
        "lastName": "Gilmore",
        "rating": 3.8,
        "rmpId": 1744576,
    },
    "Mark P Jones": {
        "fullName": "Mark P Jones",
        "firstName": "Mark",
        "lastName": "Jones",
        "rating": 4.2,
        "rmpId": 911149,
    },
    "David D Ely": {
        "fullName": "David D Ely",
        "firstName": "David",
        "lastName": "Ely",
        "rating": 3.8,
        "rmpId": 2290506,
    },
    "Mark Morrissey": {
        "fullName": "Mark Morrissey",
        "firstName": "Mark",
        "lastName": "Morrissey",
        "rating": 3.9,
        "rmpId": 1983434,
    },
    "Katie Casamento": {"fullName": "TBD"},
    "Wuchan Feng": {"fullName": "TBD"},
}

contents = [
    {
        "number": "CS 161",
        "name": "INTRO PROGRAM & PROB SOLVING",
        "crn": 10883,
        "discipline": "Computer Science",
        "days": "TR",
        "credits": 4,
        "time": "10:00 - 11:50",
        "instructor": "Mark P Jones",
        "term_description": "Fall 2019",
        "term_date": 201904,
    },
    {
        "number": "CS 161",
        "name": "INTRO PROGRAM & PROB SOLVING",
        "crn": 10883,
        "discipline": "Computer Science",
        "days": "TR",
        "credits": 4,
        "time": "10:00 - 11:50",
        "instructor": "David D Ely",
        "term_description": "Fall 2019",
        "term_date": 201904,
    },
    {
        "number": "CS 161",
        "name": "INTRO PROGRAM & PROB SOLVING",
        "crn": 10883,
        "discipline": "Computer Science",
        "days": "TR",
        "credits": 4,
        "time": "10:00 - 11:50",
        "instructor": "Wuchan Feng",
        "term_description": "Fall 2019",
        "term_date": 201904,
    },
    {
        "number": "CS 161",
        "name": "INTRO PROGRAM & PROB SOLVING",
        "crn": 10883,
        "discipline": "Computer Science",
        "days": "TR",
        "credits": 4,
        "time": "10:00 - 11:50",
        "instructor": "Mark Morrissey",
        "term_description": "Fall 2019",
        "term_date": 201904,
    },
    {
        "number": "CS 161",
        "name": "INTRO PROGRAM & PROB SOLVING",
        "crn": 10883,
        "discipline": "Computer Science",
        "days": "TR",
        "credits": 4,
        "time": "10:00 - 11:50",
        "instructor": "TBD",
        "term_description": "Fall 2019",
        "term_date": 201904,
    },
    {
        "number": "CS 161",
        "name": "INTRO PROGRAM & PROB SOLVING",
        "crn": 10883,
        "discipline": "Computer Science",
        "days": "TR",
        "credits": 4,
        "time": "10:00 - 11:50",
        "instructor": "Chris Gilmore",
        "term_description": "Fall 2019",
        "term_date": 201904,
    },
    {
        "number": "CS 161",
        "name": "INTRO PROGRAM & PROB SOLVING",
        "crn": 10883,
        "discipline": "Computer Science",
        "days": "TR",
        "credits": 4,
        "time": "10:00 - 11:50",
        "instructor": "David D Ely",
        "term_description": "Fall 2019",
        "term_date": 201904,
    },
    {
        "number": "CS 161",
        "name": "INTRO PROGRAM & PROB SOLVING",
        "crn": 10883,
        "discipline": "Computer Science",
        "days": "TR",
        "credits": 4,
        "time": "10:00 - 11:50",
        "instructor": "Katie Casamento",
        "term_description": "Fall 2019",
        "term_date": 201904,
    },
]
